# Docker compose for running services in Azure Virtual Machine
networks:
  # docker network create chatbot-networks
  chatbot-networks:
    driver: bridge

services:
  # Redis
  chatbot-redis:
    image: redis/redis-stack-server:latest
    container_name: chatbot-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/chatbot-redis-data:/data
    networks:
      - chatbot-networks

  # Celery
  chatbot-celery:
    build: ./celery
    image: chatbot-celery-worker
    container_name: chatbot-celery
    networks:
      - chatbot-networks
    environment:
      - REDIS_HOST=chatbot-redis
      - HF_HOME=/cache/huggingface
    volumes:
      - ./data/chatbot-celery-cache:/cache/huggingface
    depends_on:
      - chatbot-redis
    # GPU support. If you don't have GPU, remove the following lines
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  # MongoDB
  chatbot-mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: chatbot-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/chatbot-mongodb-data:/data/db
      - ../.docker/mongodb-config:/data/configdb
    networks:
      - chatbot-networks

  # Minio
  chatbot-minio:
    image: minio/minio
    container_name: chatbot-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/chatbot-mino-data:/data
    environment:
      MINIO_ROOT_USER: adminuser
      MINIO_ROOT_PASSWORD: adminuser
    networks:
      - chatbot-networks
    command: server --console-address ":9001" /data

  # Qdrant
  chatbot-qdrant:
    image: qdrant/qdrant:latest
    container_name: chatbot-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/chatbot-qdrant-data:/qdrant/storage
    networks:
      - chatbot-networks

  # Ollama
  chatbot-ollama:
    image: ollama/ollama:latest
    container_name: chatbot-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./data/chatbot-ollama-model:/root/.ollama
      - ../.docker/ollama-entrypoint.sh:/entrypoint.sh
    networks:
      - chatbot-networks
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    # GPU support. If you don't have GPU, remove the following lines
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  # App Services
  chatbot-app:
    build: .
    image: chatbot-app-image
    container_name: chatbot-app
    ports:
      - "7860:7860"
    networks:
      - chatbot-networks
    env_file:
      - ../.env
    environment:
      - REDIS_HOST=chatbot-redis
      - MONGODB_HOST=chatbot-mongodb
      - QDRANT_HOST=chatbot-qdrant
      - MINIO_HOST=chatbot-minio
      - LLM_OLLAMA_HOST=chatbot-ollama
      - MINIO_ACCESS_KEY=adminuser
      - MINIO_SECRET_KEY=adminuser
    depends_on:
      - chatbot-celery
      - chatbot-mongodb
      - chatbot-qdrant
      - chatbot-minio
      - chatbot-ollama
    # GPU support. If you don't have GPU, remove the following lines
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]