# Docker compose for running services locally
volumes:
  # Redis
  chatbot-redis-data:
    driver: local

  # MongoDB
  chatbot-mongodb-data:
    driver: local

  # Qdrant
  chatbot-qdrant-data:
    driver: local

  # Minio
  chatbot-mino-data:
    driver: local

  # Ollama
  chatbot-ollama-model:
    driver: local

  # Celery
  chatbot-celery-cache:
    driver: local
 
networks:
  # Chatbot Networks
  chatbot-networks:
    driver: bridge

services:
  # Redis
  chatbot-redis:
    image: redis/redis-stack-server:latest
    container_name: chatbot-redis
    restart: on-failure:2
    ports:
      - "6379:6379"
    volumes:
      - chatbot-redis-data:/data
    networks:
      - chatbot-networks

  # Celery
  chatbot-celery:
    build: ./celery
    image: chatbot-celery-worker
    container_name: chatbot-celery
    restart: on-failure:2
    networks:
      - chatbot-networks
    environment:
      - REDIS_HOST=chatbot-redis
      - HF_HOME=/cache/huggingface
    volumes:
      - chatbot-celery-cache:/cache/huggingface
    depends_on:
      - chatbot-redis
    # GPU support. If you don't have GPU, remove the following lines
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  # MongoDB
  chatbot-mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: chatbot-mongodb
    restart: on-failure:2
    ports:
      - "27017:27017"
    volumes:
      - chatbot-mongodb-data:/data/db
      - ./.docker/mongodb-config:/data/configdb
    networks:
      - chatbot-networks

  # Minio
  chatbot-minio:
    image: minio/minio
    container_name: chatbot-minio
    restart: on-failure:2
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - chatbot-mino-data:/data
    env_file:
      - .env
    networks:
      - chatbot-networks
    command: server --console-address ":9001" /data

  # Qdrant
  chatbot-qdrant:
    image: qdrant/qdrant:latest
    container_name: chatbot-qdrant
    restart: on-failure:2
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - chatbot-qdrant-data:/qdrant/storage
    networks:
      - chatbot-networks

  # Ollama
  # chatbot-ollama:
  #   image: ollama/ollama:latest
  #   container_name: chatbot-ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - chatbot-ollama-model:/root/.ollama
  #     - ./.docker/ollama-entrypoint.sh:/entrypoint.sh
  #   networks:
  #     - chatbot-networks
  #   environment:
  #     - OLLAMA_KEEP_ALIVE=24h
  #   entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
  #   # GPU support. If you don't have GPU, remove the following lines
  #   runtime: nvidia
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             capabilities: [gpu]

  # App Services
  chatbot-app:
    build: .
    image: chatbot-app-image
    container_name: chatbot-app
    restart: on-failure:2
    ports:
      - "7860:7860"
    networks:
      - chatbot-networks
    env_file:
      - .env
    environment:
      - REDIS_HOST=chatbot-redis
      - MONGODB_HOST=chatbot-mongodb
      - QDRANT_HOST=chatbot-qdrant
      - MINIO_HOST=chatbot-minio
      # - LLM_OLLAMA_HOST=chatbot-ollama
    depends_on:
      - chatbot-celery
      - chatbot-mongodb
      - chatbot-qdrant
      - chatbot-minio
      # - chatbot-ollama