# Jenkins docker compose
volumes:
  chatbot-jenkins-data:
    driver: local

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: chatbot-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: on-failure
    volumes:
      - chatbot-jenkins-data:/var/jenkins_home


# docker compose -f .jenkins/docker-compose.yml up -d