pipeline {
    agent any
    environment {
        // Define the environment variables
        REPO_URL = "git@github.com:FSG-FTI-G2/Back-end.git"
        REPO_DIR = "~/deployment/finbot"
    }
    stages {
        stage("Connect to VM via SSH") {
            environment {
                HOST_IP = credentials("finbot-azure-hostip")
            }
            steps {
                sshCommand remote: [
                    host: '${env.HOST_IP}',
                    name: 'Server',
                    credentialsId: 'finbot-azure-ssh',
                    allowAnyHosts: true
                ], command: """
                # Check if the repository directory exists
                if [ -d $REPO_DIR ]; then
                    echo "Repository directory exists, pull the latest changes"
                    cd $REPO_DIR
                    git pull origin develop
                else
                    echo "Repository directory does not exist, clone the repository"
                    git clone --single-branch --branch develop $REPO_URL $REPO_DIR
                    cd $REPO_DIR
                fi

                # Copy the .env file to the repository directory
                cp ~/aiengineer/.env $REPO_DIR/.env

                # Start the application
                docker compose -f docker-compose.yml up -d
                """
            }
        }
    }
}